[project]
name = "cachedpynetbox"
version = "1.1.0"
requires-python = ">=3.8"

license = { file="LICENSE" }
readme = "README.md"

dependencies = [
  "pynetbox",
  "requests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
